openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: A sample API for testing the TSX model generator

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [ADMIN, USER, GUEST]
        profile:
          $ref: '#/components/schemas/UserProfile'
        createdAt:
          type: string
          format: date-time
        isActive:
          type: boolean
        preferences:
          type: object
          properties:
            theme:
              type: string
              enum: [LIGHT, DARK, SYSTEM]
            notifications:
              type: boolean
        tags:
          type: array
          items:
            type: string
      required:
        - id
        - username
        - email
        - role

    UserProfile:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        age:
          type: integer
          minimum: 0
        address:
          $ref: '#/components/schemas/Address'
        bio:
          type: string
          nullable: true

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        country:
          type: string
          default: "USA"
        coordinates:
          type: object
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float

    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        inStock:
          type: boolean
        specifications:
          type: object
          additionalProperties:
            type: string
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'

    Review:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: integer
          format: int64
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
        createdAt:
          type: string
          format: date-time

    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          nullable: true
        error:
          type: object
          nullable: true
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: string 